name: Build scid

on: workflow_dispatch

jobs:
  build-scid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: run start.sh
        run: |
          chmod +x start.sh
          ./start.sh
