name: Build scid

on: workflow_dispatch

jobs:
  build-scid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: run start.sh
        run: |
          chmod +x start.sh
          sudo ./start.sh
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Create new file"
